### ISSUE TITLE
Test failure should be reported by Travis

### ISSUE THREAD

**Issue by vincent-zurczak** [linagora/angular-translate-quality#29]
That's not the case!
See https://travis-ci.org/linagora/angular-translate-quality/builds/226516806

The build is green while a unit test failed.

**Comment by vincent-zurczak** [comment]
See https://github.com/mochajs/mocha/issues/2713

**Comment by vincent-zurczak** [comment]
Postponed.

**Comment by dasilvacontin** [comment]
The `Eagerly set exitCode` fix has been released in [v3.4.2](https://github.com/mochajs/mocha/releases/tag/v3.4.2)! 🎉
